-- 有限会社 松本興業 会社予定管理システム
-- Supabase SQL Editorに貼り付けて実行してください。

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sites (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  schedule_date date not null,
  title text not null,
  place text not null default '未設定',
  color text not null default 'blue' check (color in ('blue','green','orange','purple','cyan','gray','red')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedule_employees (
  schedule_id bigint not null references public.schedules(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  primary key (schedule_id, employee_id)
);

create table if not exists public.attendance (
  attendance_date date not null,
  employee_id bigint not null references public.employees(id) on delete cascade,
  status text not null check (status in ('worker','holiday')),
  primary key (attendance_date, employee_id)
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  notice_date date not null,
  title text not null,
  body text not null default '',
  important boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  id smallint primary key default 1 check (id = 1),
  company_name text not null default '有限会社 松本興業',
  system_name text not null default '会社予定管理システム',
  show_logo_on_home boolean not null default true,
  compact_calendar boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.app_settings (id) values (1)
on conflict (id) do nothing;

alter table public.employees enable row level security;
alter table public.sites enable row level security;
alter table public.schedules enable row level security;
alter table public.schedule_employees enable row level security;
alter table public.attendance enable row level security;
alter table public.notices enable row level security;
alter table public.app_settings enable row level security;

-- 次のVer.でSupabase Authへ切り替えた後に使う、認証済みユーザー向けポリシー。
create policy "authenticated users can read employees" on public.employees for select to authenticated using (true);
create policy "authenticated users can manage employees" on public.employees for all to authenticated using (true) with check (true);
create policy "authenticated users can read sites" on public.sites for select to authenticated using (true);
create policy "authenticated users can manage sites" on public.sites for all to authenticated using (true) with check (true);
create policy "authenticated users can read schedules" on public.schedules for select to authenticated using (true);
create policy "authenticated users can manage schedules" on public.schedules for all to authenticated using (true) with check (true);
create policy "authenticated users can read schedule employees" on public.schedule_employees for select to authenticated using (true);
create policy "authenticated users can manage schedule employees" on public.schedule_employees for all to authenticated using (true) with check (true);
create policy "authenticated users can read attendance" on public.attendance for select to authenticated using (true);
create policy "authenticated users can manage attendance" on public.attendance for all to authenticated using (true) with check (true);
create policy "authenticated users can read notices" on public.notices for select to authenticated using (true);
create policy "authenticated users can manage notices" on public.notices for all to authenticated using (true) with check (true);
create policy "authenticated users can read settings" on public.app_settings for select to authenticated using (true);
create policy "authenticated users can manage settings" on public.app_settings for all to authenticated using (true) with check (true);

grant select, insert, update, delete on public.employees to authenticated;
grant select, insert, update, delete on public.sites to authenticated;
grant select, insert, update, delete on public.schedules to authenticated;
grant select, insert, update, delete on public.schedule_employees to authenticated;
grant select, insert, update, delete on public.attendance to authenticated;
grant select, insert, update, delete on public.notices to authenticated;
grant select, insert, update, delete on public.app_settings to authenticated;
grant usage, select on all sequences in schema public to authenticated;
