-- Ver.9 Step3：社員・現場・お知らせのクラウド同期
-- 注意：今回作成した4テーブルが空の状態で実行してください。
-- 以前のUUID型テーブルを、アプリと一致するbigint型へ作り直します。

drop table if exists public.schedule_employees cascade;
drop table if exists public.attendance cascade;
drop table if exists public.schedules cascade;
drop table if exists public.employees cascade;
drop table if exists public.sites cascade;
drop table if exists public.notices cascade;

create table public.employees (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.sites (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.notices (
  id bigint generated by default as identity primary key,
  notice_date date not null,
  title text not null,
  body text not null default '',
  important boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.schedules (
  id bigint generated by default as identity primary key,
  schedule_date date not null,
  title text not null,
  employee_ids bigint[] not null default '{}',
  place text not null default '未設定',
  color text not null default 'blue' check (color in ('blue','green','orange','purple','cyan','gray','red')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.employees enable row level security;
alter table public.sites enable row level security;
alter table public.notices enable row level security;
alter table public.schedules enable row level security;

create policy "temporary anon manage employees" on public.employees for all to anon using (true) with check (true);
create policy "temporary anon manage sites" on public.sites for all to anon using (true) with check (true);
create policy "temporary anon manage notices" on public.notices for all to anon using (true) with check (true);
create policy "temporary anon manage schedules" on public.schedules for all to anon using (true) with check (true);

grant select, insert, update, delete on public.employees, public.sites, public.notices, public.schedules to anon;
grant usage, select on all sequences in schema public to anon;
