-- Ver.11 Step1.4
-- 予定に登録された社内メンバーへ個人通知を送るためのテーブル

create table if not exists public.schedule_notifications (
  id bigint generated by default as identity primary key,
  target_profile_id uuid not null references public.profiles(id) on delete cascade,
  notification_type text not null check (notification_type in ('schedule_created','schedule_updated','schedule_deleted')),
  title text not null,
  body text not null default '',
  schedule_id bigint null,
  is_read boolean not null default false,
  read_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists schedule_notifications_target_profile_id_idx
  on public.schedule_notifications(target_profile_id, created_at desc);

alter table public.schedule_notifications enable row level security;

drop policy if exists "schedule_notifications_select_own" on public.schedule_notifications;
create policy "schedule_notifications_select_own"
on public.schedule_notifications for select
to authenticated
using (target_profile_id = auth.uid());

drop policy if exists "schedule_notifications_update_own" on public.schedule_notifications;
create policy "schedule_notifications_update_own"
on public.schedule_notifications for update
to authenticated
using (target_profile_id = auth.uid())
with check (target_profile_id = auth.uid());

drop policy if exists "schedule_notifications_insert_admin" on public.schedule_notifications;
create policy "schedule_notifications_insert_admin"
on public.schedule_notifications for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.active = true
  )
);

-- Realtimeは次のStepで有効化するので、今回は追加しません。
